import { type Href, useRouter } from 'expo-router';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { FarmerState } from '@/components/farmer/farmer-state';
import { BrandColors } from '@/constants/theme';
import { useFarmerProducts } from '@/hooks/use-farmer-products';

export default function FarmerFutureHarvestScreen() {
  const router = useRouter();
  const { error, isLoading, products, refresh } = useFarmerProducts('future');
  if (isLoading && products.length === 0) return <FarmerState isLoading />;
  if (error && products.length === 0) return <FarmerState error={error} onRetry={refresh} />;
  return <SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl onRefresh={refresh} refreshing={isLoading} />}><View style={styles.header}><Pressable onPress={router.back}><Text style={styles.back}>‹</Text></Pressable><View><Text style={styles.brand}>Farm</Text><Text style={styles.title}>Harvest Schedule</Text></View></View><Text style={styles.sectionTitle}>Upcoming & Current Yields</Text>{products.length > 0 ? products.map((product) => <Pressable key={product._id} onPress={() => router.push(`/farmer/products/${product._id}` as Href)} style={styles.card}><View style={styles.cardHeader}><Text style={styles.name}>{product.name}</Text><View style={styles.badge}><Text style={styles.badgeText}>{product.status}</Text></View></View><Text style={styles.detail}>Expected: {product.harvestDate ? new Date(product.harvestDate).toLocaleDateString('en-LK') : 'Not set'}</Text><Text style={styles.detail}>Estimated Yield: <Text style={styles.strong}>{product.availableQuantity.toLocaleString('en-LK')} {product.unit}</Text></Text><Text style={styles.detail}>{product.farmLocation.city ? `${product.farmLocation.city}, ` : ''}{product.farmLocation.district}</Text><View style={styles.preorder}><Text style={styles.preorderText}>{product.status === 'active' ? 'Listed for Pre-order' : 'Edit Harvest Listing'}</Text></View></Pressable>) : <FarmerState emptyMessage="Future harvest listings will appear here." />}<Pressable onPress={() => router.push('/farmer/products/new?listingType=future' as Href)} style={styles.add}><Text style={styles.addText}>List a Future Harvest</Text></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { backgroundColor: '#FAFCFA', flex: 1 }, content: { padding: 16, paddingBottom: 35 }, header: { alignItems: 'center', flexDirection: 'row', marginTop: 7 }, back: { color: BrandColors.primary, fontSize: 36, marginRight: 10 }, brand: { color: BrandColors.primary, fontSize: 25, fontWeight: '800' }, title: { color: BrandColors.primary, fontSize: 15, fontWeight: '800', marginTop: -4 }, sectionTitle: { color: '#4D504D', fontSize: 14, fontWeight: '800', marginTop: 19 }, card: { backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 14, borderWidth: 1, marginTop: 12, padding: 15 }, cardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, name: { color: BrandColors.primary, fontSize: 14, fontWeight: '800' }, badge: { backgroundColor: '#FFF3CD', borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, badgeText: { color: BrandColors.warning, fontSize: 8, fontWeight: '800', textTransform: 'capitalize' }, detail: { color: '#858885', fontSize: 11, marginTop: 8 }, strong: { color: '#494C49', fontWeight: '800' }, preorder: { alignItems: 'center', backgroundColor: BrandColors.primarySoft, borderRadius: 10, marginTop: 13, paddingVertical: 10 }, preorderText: { color: BrandColors.primary, fontSize: 10, fontWeight: '800' }, add: { alignItems: 'center', backgroundColor: BrandColors.primary, borderRadius: 24, marginTop: 17, paddingVertical: 14 }, addText: { color: BrandColors.white, fontSize: 12, fontWeight: '800' } });
