import { type Href, useRouter } from 'expo-router';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { FarmerProductTile } from '@/components/farmer/product-tile';
import { FarmerState } from '@/components/farmer/farmer-state';
import { BrandColors } from '@/constants/theme';
import { useAuth } from '@/contexts/auth-context';
import { useFarmerProducts } from '@/hooks/use-farmer-products';
import { useFarmerProfile } from '@/hooks/use-farmer-profile';

export default function FarmerDashboardScreen() {
  const router = useRouter();
  const { user } = useAuth();
  const profileState = useFarmerProfile();
  const productState = useFarmerProducts();
  const refresh = () => { profileState.refresh(); productState.refresh(); };
  if ((profileState.isLoading || productState.isLoading) && productState.products.length === 0) return <FarmerState isLoading />;
  if (productState.error && productState.products.length === 0) return <FarmerState error={productState.error} onRetry={refresh} />;
  const active = productState.products.filter((item) => item.status === 'active');
  const future = productState.products.filter((item) => item.listingType === 'future');
  return <SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl onRefresh={refresh} refreshing={profileState.isLoading || productState.isLoading} />}><View style={styles.header}><View><Text style={styles.brand}>Farm</Text><Text style={styles.greeting}>Ayubowan, {user?.name.split(' ')[0]}</Text><Text style={styles.location}>{profileState.profile ? `${profileState.profile.farmName} · ${profileState.profile.farmLocation.district}` : 'Complete your farm profile'}</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>{user?.name.charAt(0)}</Text></View></View>{!profileState.profile ? <Pressable onPress={() => router.push('/(app)/farmer/profile' as Href)} style={styles.setup}><View><Text style={styles.setupTitle}>Set up your Farmer Profile</Text><Text style={styles.setupText}>Add farm location and contact details before listing products.</Text></View><Text style={styles.arrow}>›</Text></Pressable> : null}<View style={styles.metrics}><Metric label="Listed Items" value={String(productState.products.length)} /><Metric label="Active" value={String(active.length)} /><Metric label="Future Harvests" value={String(future.length)} /></View><View style={styles.actionRow}><Action label="Add Product" onPress={() => router.push('/farmer/products/new' as Href)} /><Action label="Future Harvests" onPress={() => router.push('/farmer/products/future' as Href)} /></View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>My Recent Products</Text><Pressable onPress={() => router.push('/(app)/farmer/products' as Href)}><Text style={styles.viewAll}>View All</Text></Pressable></View>{productState.products.length > 0 ? <View style={styles.grid}>{productState.products.slice(0, 2).map((product) => <FarmerProductTile key={product._id} product={product} onPress={() => router.push(`/farmer/products/${product._id}` as Href)} />)}</View> : <FarmerState emptyMessage="List your first current product or future harvest." />}</ScrollView></SafeAreaView>;
}

function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
function Action({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.action}><Text style={styles.actionText}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ safeArea: { backgroundColor: '#FAFCFA', flex: 1 }, content: { padding: 16, paddingBottom: 30 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }, brand: { color: BrandColors.primary, fontSize: 28, fontWeight: '800' }, greeting: { color: '#444744', fontSize: 17, fontWeight: '800', marginTop: 3 }, location: { color: '#929592', fontSize: 10, marginTop: 3 }, avatar: { alignItems: 'center', backgroundColor: BrandColors.primarySoft, borderRadius: 24, height: 48, justifyContent: 'center', width: 48 }, avatarText: { color: BrandColors.primary, fontSize: 20, fontWeight: '800' }, setup: { alignItems: 'center', backgroundColor: '#FFF5D8', borderRadius: 12, flexDirection: 'row', justifyContent: 'space-between', marginTop: 16, padding: 13 }, setupTitle: { color: '#855F08', fontSize: 12, fontWeight: '800' }, setupText: { color: '#937D48', fontSize: 9, marginTop: 3, maxWidth: 290 }, arrow: { color: '#855F08', fontSize: 24 }, metrics: { flexDirection: 'row', gap: 8, marginTop: 16 }, metric: { backgroundColor: BrandColors.primarySurface, borderRadius: 12, flex: 1, padding: 12 }, metricLabel: { color: '#8C8F8C', fontSize: 8 }, metricValue: { color: BrandColors.primary, fontSize: 17, fontWeight: '800', marginTop: 6 }, actionRow: { flexDirection: 'row', gap: 9, marginTop: 14 }, action: { alignItems: 'center', backgroundColor: BrandColors.primary, borderRadius: 11, flex: 1, paddingVertical: 13 }, actionText: { color: BrandColors.white, fontSize: 11, fontWeight: '800' }, sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 20 }, sectionTitle: { color: '#474A47', fontSize: 14, fontWeight: '800' }, viewAll: { color: BrandColors.primary, fontSize: 10, fontWeight: '800' }, grid: { flexDirection: 'row', gap: 10, marginTop: 11 } });
