import { useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { FarmerState } from '@/components/farmer/farmer-state';
import { BrandColors } from '@/constants/theme';
import { useFarmerOrders } from '@/hooks/use-farmer-orders';
import { getApiErrorMessage } from '@/services/api';
import { updateFarmerOrderStatus } from '@/services/farmer-service';
import type { BuyerOrder, OrderStatus } from '@/types/transactions';
import { formatLkr } from '@/utils/formatters';

type OrderFilter = 'all' | 'active' | 'completed' | 'cancelled';
const activeStatuses: OrderStatus[] = ['pending', 'confirmed', 'preparing', 'dispatched', 'inTransit'];

export default function FarmerOrdersScreen() {
  const state = useFarmerOrders(); const [filter, setFilter] = useState<OrderFilter>('all'); const [busyId, setBusyId] = useState<string | null>(null); const [actionError, setActionError] = useState<string | null>(null);
  const visible = useMemo(() => state.orders.filter((order) => filter === 'all' || (filter === 'active' && activeStatuses.includes(order.status)) || (filter === 'completed' && order.status === 'delivered') || (filter === 'cancelled' && order.status === 'cancelled')), [filter, state.orders]);
  if (state.isLoading && state.orders.length === 0) return <FarmerState isLoading />; if (state.error && state.orders.length === 0) return <FarmerState error={state.error} onRetry={state.refresh} />;
  const update = async (order: BuyerOrder, status: 'confirmed' | 'preparing' | 'dispatched') => { setBusyId(order._id); setActionError(null); try { const changed = await updateFarmerOrderStatus(order._id, status); state.setOrders((current) => current.map((item) => item._id === changed._id ? changed : item)); } catch (error) { setActionError(getApiErrorMessage(error)); } finally { setBusyId(null); } };
  return <SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl onRefresh={state.refresh} refreshing={state.isLoading} />}><Text style={styles.brand}>Farm</Text><Text style={styles.title}>Orders Management</Text><View style={styles.filters}>{(['all', 'active', 'completed', 'cancelled'] as OrderFilter[]).map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.activeFilter]}><Text style={[styles.filterText, filter === item && styles.activeFilterText]}>{capitalize(item)}</Text></Pressable>)}</View>{actionError ? <Text style={styles.error}>{actionError}</Text> : null}{visible.length > 0 ? visible.map((order) => <OrderCard busy={busyId === order._id} key={order._id} onUpdate={(status) => update(order, status)} order={order} />) : <FarmerState emptyMessage="No farmer orders match this filter." />}</ScrollView></SafeAreaView>;
}

function OrderCard({ busy, onUpdate, order }: { busy: boolean; onUpdate: (status: 'confirmed' | 'preparing' | 'dispatched') => void; order: BuyerOrder }) { const product = typeof order.product === 'string' ? null : order.product; const buyer = typeof order.buyer === 'string' ? 'Registered buyer' : order.buyer.name; const next = order.status === 'pending' ? { label: 'Confirm Order', status: 'confirmed' as const } : order.status === 'confirmed' ? { label: 'Start Preparing', status: 'preparing' as const } : order.status === 'preparing' ? { label: 'Mark Dispatched', status: 'dispatched' as const } : null; return <View style={styles.card}><View style={styles.cardHeader}><Text style={styles.orderCode}>Order ID: {order.orderCode}</Text><View style={styles.status}><Text style={styles.statusText}>{order.status}</Text></View></View><Text style={styles.product}>{product?.name ?? 'Farm Product'}</Text><Text style={styles.buyer}>Buyer: {buyer}</Text><Text style={styles.details}>Qty: {order.quantity.toLocaleString('en-LK')} {order.unit} · Total: <Text style={styles.amount}>{formatLkr(order.totalAmount)}</Text></Text><Text style={styles.date}>{new Date(order.createdAt).toLocaleDateString('en-LK')}</Text>{next ? <Pressable disabled={busy} onPress={() => onUpdate(next.status)} style={styles.action}><Text style={styles.actionText}>{busy ? 'Updating...' : next.label}</Text></Pressable> : null}</View>; }
function capitalize(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
const styles = StyleSheet.create({ safeArea: { backgroundColor: '#FAFCFA', flex: 1 }, content: { padding: 16, paddingBottom: 35 }, brand: { color: BrandColors.primary, fontSize: 27, fontWeight: '800', marginTop: 8 }, title: { color: BrandColors.primary, fontSize: 16, fontWeight: '800', marginTop: -3 }, filters: { flexDirection: 'row', gap: 7, marginVertical: 15 }, filter: { backgroundColor: BrandColors.primarySoft, borderRadius: 17, paddingHorizontal: 11, paddingVertical: 8 }, activeFilter: { backgroundColor: BrandColors.primary }, filterText: { color: BrandColors.primary, fontSize: 9, fontWeight: '800' }, activeFilterText: { color: BrandColors.white }, error: { color: BrandColors.danger, fontSize: 10, marginBottom: 8, textAlign: 'center' }, card: { backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 14, borderWidth: 1, marginBottom: 12, padding: 15 }, cardHeader: { alignItems: 'center', borderBottomColor: BrandColors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 10 }, orderCode: { color: '#555855', fontSize: 11, fontWeight: '800' }, status: { backgroundColor: BrandColors.primarySoft, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, statusText: { color: BrandColors.primary, fontSize: 8, fontWeight: '800', textTransform: 'capitalize' }, product: { color: BrandColors.primary, fontSize: 13, fontWeight: '800', marginTop: 12 }, buyer: { color: '#686B68', fontSize: 10, marginTop: 5 }, details: { color: '#8F928F', fontSize: 10, marginTop: 6 }, amount: { color: BrandColors.primary, fontWeight: '800' }, date: { color: '#A0A3A0', fontSize: 9, marginTop: 10 }, action: { alignItems: 'center', backgroundColor: BrandColors.primary, borderRadius: 9, marginTop: 11, paddingVertical: 10 }, actionText: { color: BrandColors.white, fontSize: 10, fontWeight: '800' } });
