import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { FormField } from '@/components/auth/form-field';
import { PrimaryButton } from '@/components/auth/primary-button';
import { FarmerState } from '@/components/farmer/farmer-state';
import { BrandColors } from '@/constants/theme';
import { useAuth } from '@/contexts/auth-context';
import { useFarmerProducts } from '@/hooks/use-farmer-products';
import { useFarmerProfile } from '@/hooks/use-farmer-profile';
import { getApiErrorMessage } from '@/services/api';
import { createFarmerProfile } from '@/services/farmer-service';

export default function FarmerProfileScreen() {
  const { logout, user } = useAuth(); const profileState = useFarmerProfile(); const productsState = useFarmerProducts();
  const [phone, setPhone] = useState(''); const [farmName, setFarmName] = useState(''); const [address, setAddress] = useState(''); const [city, setCity] = useState(''); const [district, setDistrict] = useState(''); const [farmSize, setFarmSize] = useState(''); const [crops, setCrops] = useState(''); const [error, setError] = useState<string | null>(null); const [isSaving, setIsSaving] = useState(false);
  if (profileState.isLoading && !profileState.profile) return <FarmerState isLoading />;
  const save = async () => { const size = farmSize ? Number(farmSize) : undefined; if (!phone.trim() || !farmName.trim() || !city.trim() || !district.trim() || (size !== undefined && (!Number.isFinite(size) || size <= 0))) { setError('Phone, farm name, city, district, and valid farm size are required.'); return; } setIsSaving(true); setError(null); try { await createFarmerProfile({ phone: phone.trim(), farmName: farmName.trim(), farmLocation: { addressLine: address.trim() || undefined, city: city.trim(), district: district.trim() }, farmSizeAcres: size, mainCrops: crops.split(',').map((item) => item.trim()).filter(Boolean) }); profileState.refresh(); } catch (requestError) { setError(getApiErrorMessage(requestError)); } finally { setIsSaving(false); } };
  const profile = profileState.profile; const activeCount = productsState.products.filter((item) => item.status === 'active').length;
  return <SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.brand}>Farm</Text><Text style={styles.title}>Farmer Profile</Text><View style={styles.identity}><View style={styles.avatar}><Text style={styles.avatarText}>{user?.name.charAt(0)}</Text></View><View><Text style={styles.name}>{user?.name}</Text><Text style={styles.email}>{user?.email}</Text>{profile ? <Text style={styles.verified}>PROFILE ACTIVE</Text> : <Text style={styles.required}>SETUP REQUIRED</Text>}</View></View>{profile ? <><View style={styles.metrics}><Metric label="Listed Items" value={String(productsState.products.length)} /><Metric label="Active Listings" value={String(activeCount)} /></View><View style={styles.card}><Row label="Farm" value={profile.farmName} /><Row label="Phone" value={profile.phone} /><Row label="Location" value={`${profile.farmLocation.city}, ${profile.farmLocation.district}`} /><Row label="Farm size" value={profile.farmSizeAcres ? `${profile.farmSizeAcres} acres` : 'Not set'} /><Row label="Main crops" value={profile.mainCrops.join(', ') || 'Not set'} /></View></> : <View style={styles.form}><Text style={styles.formTitle}>Complete Farm Details</Text><FormField keyboardType="phone-pad" label="Phone" onChangeText={setPhone} placeholder="077 123 4567" value={phone} /><FormField autoCapitalize="words" label="Farm Name" onChangeText={setFarmName} placeholder="Bandara Farms" value={farmName} /><FormField autoCapitalize="words" label="Address" onChangeText={setAddress} placeholder="Farm road" value={address} /><View style={styles.row}><View style={styles.flex}><FormField autoCapitalize="words" label="City" onChangeText={setCity} placeholder="Kandy" value={city} /></View><View style={styles.flex}><FormField autoCapitalize="words" label="District" onChangeText={setDistrict} placeholder="Kandy" value={district} /></View></View><FormField keyboardType="numeric" label="Farm Size (acres)" onChangeText={setFarmSize} placeholder="2.5" value={farmSize} /><FormField autoCapitalize="words" label="Main Crops" onChangeText={setCrops} placeholder="Rice, Pepper, Carrots" value={crops} />{error || profileState.error ? <Text style={styles.error}>{error ?? profileState.error}</Text> : null}<PrimaryButton label="Save Farmer Profile" loading={isSaving} onPress={save} /></View>}<Pressable onPress={logout} style={styles.logout}><Text style={styles.logoutText}>Log Out</Text></Pressable></ScrollView></SafeAreaView>;
}

function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; } function Row({ label, value }: { label: string; value: string }) { return <View style={styles.infoRow}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ safeArea: { backgroundColor: '#FAFCFA', flex: 1 }, content: { padding: 16, paddingBottom: 35 }, brand: { color: BrandColors.primary, fontSize: 27, fontWeight: '800', marginTop: 8 }, title: { color: BrandColors.primary, fontSize: 16, fontWeight: '800', marginTop: -3 }, identity: { alignItems: 'center', backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 14, borderWidth: 1, flexDirection: 'row', marginTop: 17, padding: 15 }, avatar: { alignItems: 'center', backgroundColor: BrandColors.primarySoft, borderRadius: 29, height: 58, justifyContent: 'center', marginRight: 12, width: 58 }, avatarText: { color: BrandColors.primary, fontSize: 23, fontWeight: '800' }, name: { color: '#454845', fontSize: 16, fontWeight: '800' }, email: { color: '#949794', fontSize: 10, marginTop: 3 }, verified: { color: BrandColors.primary, fontSize: 8, fontWeight: '800', marginTop: 5 }, required: { color: BrandColors.warning, fontSize: 8, fontWeight: '800', marginTop: 5 }, metrics: { flexDirection: 'row', gap: 10, marginTop: 15 }, metric: { alignItems: 'center', backgroundColor: BrandColors.primarySurface, borderRadius: 12, flex: 1, padding: 14 }, metricLabel: { color: '#909390', fontSize: 9 }, metricValue: { color: BrandColors.primary, fontSize: 16, fontWeight: '800', marginTop: 5 }, card: { backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 14, borderWidth: 1, marginTop: 15, padding: 14 }, infoRow: { borderBottomColor: BrandColors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 11 }, infoLabel: { color: '#8D908D', fontSize: 10 }, infoValue: { color: '#474A47', flex: 1, fontSize: 11, fontWeight: '700', marginLeft: 10, textAlign: 'right' }, form: { gap: 14, marginTop: 17 }, formTitle: { color: '#474A47', fontSize: 14, fontWeight: '800' }, row: { flexDirection: 'row', gap: 9 }, flex: { flex: 1 }, error: { color: BrandColors.danger, fontSize: 11, textAlign: 'center' }, logout: { alignItems: 'center', backgroundColor: '#FEE2E2', borderRadius: 11, marginTop: 18, paddingVertical: 13 }, logoutText: { color: BrandColors.danger, fontSize: 12, fontWeight: '800' } });
