import { useMemo, useState } from 'react';
import { type Href, useRouter } from 'expo-router';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AdvisoryState } from '@/components/advisory/advisory-state';
import { BrandColors } from '@/constants/theme';
import { useQualityGuidelines } from '@/hooks/use-advisory-guidance';
import { getApiErrorMessage } from '@/services/api';
import { archiveQualityGuideline } from '@/services/advisory-service';
import type { QualityGuideline } from '@/types/advisory';

export default function QualityGuidelinesScreen() {
  const router = useRouter(); const state = useQualityGuidelines(); const [search, setSearch] = useState(''); const [busyId, setBusyId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const visible = useMemo(() => { const term = search.trim().toLowerCase(); return state.guidelines.filter((item) => !term || `${item.cropName} ${item.growingRegion ?? ''} ${item.requiredCertification}`.toLowerCase().includes(term)); }, [search, state.guidelines]);
  const archive = async (item: QualityGuideline) => { setBusyId(item._id); setError(null); try { await archiveQualityGuideline(item._id); state.setGuidelines((current) => current.filter((guideline) => guideline._id !== item._id)); } catch (requestError) { setError(getApiErrorMessage(requestError)); } finally { setBusyId(null); } };
  return <SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl onRefresh={state.refresh} refreshing={state.isLoading} />}><View style={styles.header}><Pressable onPress={router.back}><Text style={styles.back}>‹</Text></Pressable><View style={styles.headerCopy}><Text style={styles.title}>Quality Guidelines & Standards</Text><Text style={styles.subtitle}>Approved crop grading metrics</Text></View><Pressable onPress={() => router.push('/(app)/officer/notices/quality-new' as Href)} style={styles.add}><Text style={styles.addText}>＋</Text></Pressable></View><View style={styles.searchBox}><Text style={styles.searchIcon}>⌕</Text><TextInput onChangeText={setSearch} placeholder="Search crops or certifications..." placeholderTextColor="#A1A4A1" style={styles.search} value={search} /></View><View style={styles.sectionRow}><Text style={styles.sectionTitle}>Active Crop Standards</Text><Text style={styles.updated}>Updated: {new Date().toLocaleDateString('en-LK')}</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}{visible.length > 0 ? visible.map((item) => <GuidelineCard busy={busyId === item._id} item={item} key={item._id} onArchive={() => archive(item)} />) : <AdvisoryState emptyMessage="No active quality guidelines match this search." error={state.error} isLoading={state.isLoading} onRetry={state.refresh} />}</ScrollView></SafeAreaView>;
}
function GuidelineCard({ busy, item, onArchive }: { busy: boolean; item: QualityGuideline; onArchive: () => void }) { return <View style={styles.card}><View style={styles.cardHeader}><View><Text style={styles.crop}>{item.cropName}</Text>{item.growingRegion ? <Text style={styles.region}>{item.growingRegion}</Text> : null}</View><Pressable disabled={busy} onPress={onArchive}><Text style={styles.archive}>{busy ? '...' : 'Archive'}</Text></Pressable></View><View style={styles.metrics}><Metric label="MAX MOISTURE" value={item.maxMoisture} /><Metric label="MIN PURITY" value={item.minPurity} /><Metric label="SIZING / GRADE" value={item.sizingGrade} /><Metric green label="REQUIRED CERT" value={item.requiredCertification} /></View></View>; }
function Metric({ green, label, value }: { green?: boolean; label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, green && styles.greenValue]}>{value}</Text></View>; }
const styles = StyleSheet.create({ safeArea: { backgroundColor: '#FAFCFA', flex: 1 }, content: { padding: 16, paddingBottom: 34 }, header: { alignItems: 'center', flexDirection: 'row', minHeight: 66 }, back: { color: BrandColors.primary, fontSize: 36, marginRight: 9 }, headerCopy: { flex: 1 }, title: { color: BrandColors.primary, fontSize: 17, fontWeight: '800' }, subtitle: { color: '#999C99', fontSize: 9, marginTop: 3 }, add: { alignItems: 'center', backgroundColor: BrandColors.primarySoft, borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }, addText: { color: BrandColors.primary, fontSize: 20, fontWeight: '800' }, searchBox: { alignItems: 'center', backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 21, borderWidth: 1, flexDirection: 'row', marginTop: 8, paddingHorizontal: 12 }, searchIcon: { color: '#969996', fontSize: 19 }, search: { color: '#454845', flex: 1, fontSize: 11, minHeight: 42, paddingHorizontal: 7 }, sectionRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginVertical: 16 }, sectionTitle: { color: '#555855', fontSize: 11, fontWeight: '800' }, updated: { color: BrandColors.primary, fontSize: 8, fontWeight: '700' }, error: { color: BrandColors.danger, fontSize: 10, marginBottom: 8, textAlign: 'center' }, card: { backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 14, borderWidth: 1, marginBottom: 11, padding: 13 }, cardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, crop: { color: '#444744', fontSize: 12, fontWeight: '800' }, region: { color: '#999C99', fontSize: 8, marginTop: 3 }, archive: { color: BrandColors.danger, fontSize: 8, fontWeight: '800' }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }, metric: { backgroundColor: '#F6F7F6', borderRadius: 8, padding: 9, width: '48%' }, metricLabel: { color: '#999C99', fontSize: 7 }, metricValue: { color: '#555855', fontSize: 10, fontWeight: '800', marginTop: 5 }, greenValue: { color: BrandColors.primary } });
