import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { BrandColors } from '@/constants/theme';
import { getApiErrorMessage } from '@/services/api';
import { createQualityGuideline } from '@/services/advisory-service';

export default function CreateQualityGuidelineScreen() {
  const router = useRouter(); const [cropName, setCropName] = useState(''); const [region, setRegion] = useState(''); const [moisture, setMoisture] = useState(''); const [purity, setPurity] = useState(''); const [grade, setGrade] = useState(''); const [certification, setCertification] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const submit = async () => { if ([cropName, moisture, purity, grade, certification].some((item) => item.trim().length < 2)) { setError('Complete all required quality standard fields.'); return; } setBusy(true); setError(null); try { await createQualityGuideline({ cropName: cropName.trim(), growingRegion: region.trim() || undefined, maxMoisture: moisture.trim(), minPurity: purity.trim(), sizingGrade: grade.trim(), requiredCertification: certification.trim() }); router.back(); } catch (requestError) { setError(getApiErrorMessage(requestError)); } finally { setBusy(false); } };
  return <SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable onPress={router.back}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Add Quality Standard</Text></View><Label text="Crop Name" /><Input onChangeText={setCropName} placeholder="e.g. Keeri Samba Rice" value={cropName} /><Label text="Growing Region (optional)" /><Input onChangeText={setRegion} placeholder="e.g. Polonnaruwa" value={region} /><View style={styles.row}><View style={styles.half}><Label text="Maximum Moisture" /><Input onChangeText={setMoisture} placeholder="< 14%" value={moisture} /></View><View style={styles.half}><Label text="Minimum Purity" /><Input onChangeText={setPurity} placeholder="99.2%" value={purity} /></View></View><Label text="Sizing / Grade Standard" /><Input onChangeText={setGrade} placeholder="Grade Standard 3.8mm" value={grade} /><Label text="Required Certification" /><Input onChangeText={setCertification} placeholder="DOA Sri Lanka Organic" value={certification} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={busy} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{busy ? 'Saving...' : 'Publish Quality Standard'}</Text></Pressable></ScrollView></SafeAreaView>;
}
function Label({ text }: { text: string }) { return <Text style={styles.label}>{text}</Text>; }
function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput placeholderTextColor="#A1A4A1" style={styles.input} {...props} />; }
const styles = StyleSheet.create({ safeArea: { backgroundColor: '#FAFCFA', flex: 1 }, content: { padding: 16, paddingBottom: 34 }, header: { alignItems: 'center', flexDirection: 'row', minHeight: 66 }, back: { color: BrandColors.primary, fontSize: 36, marginRight: 11 }, title: { color: BrandColors.primary, fontSize: 19, fontWeight: '800' }, label: { color: '#555855', fontSize: 10, fontWeight: '800', marginBottom: 7, marginTop: 14 }, input: { backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 9, borderWidth: 1, color: '#454845', fontSize: 11, minHeight: 43, paddingHorizontal: 11 }, row: { flexDirection: 'row', gap: 10 }, half: { flex: 1 }, error: { color: BrandColors.danger, fontSize: 10, marginTop: 11, textAlign: 'center' }, submit: { alignItems: 'center', backgroundColor: BrandColors.primary, borderRadius: 11, marginTop: 18, paddingVertical: 15 }, submitText: { color: BrandColors.white, fontSize: 11, fontWeight: '800' } });
