import { type Href, useRouter } from 'expo-router';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AdvisoryState } from '@/components/advisory/advisory-state';
import { BrandColors } from '@/constants/theme';
import { useSurplusAdvisories } from '@/hooks/use-advisory-guidance';
import { getApiErrorMessage } from '@/services/api';
import { resolveSurplusAdvisory } from '@/services/advisory-service';
import type { SurplusAdvisory } from '@/types/advisory';
import { useState } from 'react';

const levelStyle = { critical: { background: '#FFE4E4', text: BrandColors.danger, label: 'Critical Surplus' }, moderate: { background: '#FFF0C9', text: BrandColors.warning, label: 'Moderate Surplus' }, normal: { background: BrandColors.primarySoft, text: BrandColors.primary, label: 'Normal / Stable' } };

export default function MarketSurplusScreen() {
  const router = useRouter(); const state = useSurplusAdvisories(); const [busyId, setBusyId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const resolve = async (item: SurplusAdvisory) => { setBusyId(item._id); setError(null); try { await resolveSurplusAdvisory(item._id); state.setAdvisories((current) => current.filter((advisory) => advisory._id !== item._id)); } catch (requestError) { setError(getApiErrorMessage(requestError)); } finally { setBusyId(null); } };
  return <SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl onRefresh={state.refresh} refreshing={state.isLoading} />}><View style={styles.header}><Pressable onPress={router.back}><Text style={styles.back}>‹</Text></Pressable><View><Text style={styles.title}>Market Surplus Advisory</Text><Text style={styles.subtitle}>Surplus mitigation and farmer guidance</Text></View></View><View style={styles.createBanner}><View style={styles.createCopy}><Text style={styles.createTitle}>Create New Advisory</Text><Text style={styles.createText}>Draft advice on crop diversion or harvesting delays</Text></View><Pressable onPress={() => router.push('/(app)/officer/notices/surplus-new' as Href)} style={styles.createButton}><Text style={styles.createButtonText}>Issue Advice</Text></Pressable></View><Text style={styles.sectionTitle}>Active Surplus Advisories ({state.advisories.length})</Text>{error ? <Text style={styles.error}>{error}</Text> : null}{state.advisories.length > 0 ? state.advisories.map((item) => <AdvisoryCard busy={busyId === item._id} item={item} key={item._id} onResolve={() => resolve(item)} />) : <AdvisoryState emptyMessage="No active market surplus advisories." error={state.error} isLoading={state.isLoading} onRetry={state.refresh} />}{state.advisories[0]?.recommendedActions.length ? <View style={styles.recommendationCard}><Text style={styles.recommendationTitle}>Recommended Actions for {state.advisories[0].cropName} Farmers</Text>{state.advisories[0].recommendedActions.map((action, index) => <Text key={`${action}-${index}`} style={styles.recommendation}>{index + 1}. {action}</Text>)}</View> : null}</ScrollView></SafeAreaView>;
}

function AdvisoryCard({ busy, item, onResolve }: { busy: boolean; item: SurplusAdvisory; onResolve: () => void }) { const colors = levelStyle[item.level]; return <View style={styles.card}><View style={styles.cardHeader}><Text style={styles.crop}>{item.cropName}{item.harvestSeason ? ` (${item.harvestSeason})` : ''}</Text><View style={[styles.levelBadge, { backgroundColor: colors.background }]}><Text style={[styles.levelText, { color: colors.text }]}>{colors.label}</Text></View></View><Text style={styles.detail}>Affected Districts: <Text style={styles.detailStrong}>{item.affectedDistricts.join(', ')}</Text></Text><Text style={styles.detail}>Surplus Volume: <Text style={styles.detailStrong}>{item.surplusVolumeMt.toLocaleString('en-LK')} MT</Text></Text><Text style={styles.detail}>Price Impact Trend: <Text style={styles.impact}>{item.priceImpactPercent > 0 ? '+' : ''}{item.priceImpactPercent}%</Text></Text><Pressable disabled={busy} onPress={onResolve} style={styles.resolve}><Text style={styles.resolveText}>{busy ? 'Updating...' : 'Mark Resolved'}</Text></Pressable></View>; }
const styles = StyleSheet.create({ safeArea: { backgroundColor: '#FAFCFA', flex: 1 }, content: { padding: 16, paddingBottom: 34 }, header: { alignItems: 'center', flexDirection: 'row', minHeight: 66 }, back: { color: BrandColors.primary, fontSize: 36, marginRight: 11 }, title: { color: BrandColors.primary, fontSize: 19, fontWeight: '800' }, subtitle: { color: '#999C99', fontSize: 9, marginTop: 3 }, createBanner: { alignItems: 'center', backgroundColor: BrandColors.primary, borderRadius: 12, flexDirection: 'row', marginTop: 8, padding: 15 }, createCopy: { flex: 1 }, createTitle: { color: BrandColors.white, fontSize: 12, fontWeight: '800' }, createText: { color: '#D8F1E1', fontSize: 9, lineHeight: 14, marginTop: 4 }, createButton: { backgroundColor: BrandColors.white, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10 }, createButtonText: { color: BrandColors.primary, fontSize: 9, fontWeight: '800' }, sectionTitle: { color: '#555855', fontSize: 12, fontWeight: '800', marginBottom: 10, marginTop: 17 }, error: { color: BrandColors.danger, fontSize: 10, marginBottom: 8, textAlign: 'center' }, card: { backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 13, borderWidth: 1, marginBottom: 10, padding: 13 }, cardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }, crop: { color: '#444744', flex: 1, fontSize: 12, fontWeight: '800', marginRight: 8 }, levelBadge: { borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, levelText: { fontSize: 7, fontWeight: '800' }, detail: { color: '#858885', fontSize: 10, marginTop: 5 }, detailStrong: { color: '#555855', fontWeight: '800' }, impact: { color: BrandColors.danger, fontWeight: '800' }, resolve: { alignItems: 'center', borderColor: BrandColors.primary, borderRadius: 8, borderWidth: 1, marginTop: 10, paddingVertical: 8 }, resolveText: { color: BrandColors.primary, fontSize: 8, fontWeight: '800' }, recommendationCard: { backgroundColor: '#F6F7F6', borderRadius: 12, marginTop: 5, padding: 13 }, recommendationTitle: { color: '#454845', fontSize: 11, fontWeight: '800', marginBottom: 7 }, recommendation: { color: '#606360', fontSize: 9, lineHeight: 14, marginTop: 3 } });
