import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { BrandColors } from '@/constants/theme';
import { getApiErrorMessage } from '@/services/api';
import { createSurplusAdvisory } from '@/services/advisory-service';
import type { SurplusAdvisory } from '@/types/advisory';

export default function CreateSurplusAdvisoryScreen() {
  const router = useRouter(); const [cropName, setCropName] = useState(''); const [harvestSeason, setHarvestSeason] = useState(''); const [districts, setDistricts] = useState(''); const [volume, setVolume] = useState(''); const [impact, setImpact] = useState(''); const [level, setLevel] = useState<SurplusAdvisory['level']>('moderate'); const [actions, setActions] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const submit = async () => { const surplusVolumeMt = Number(volume); const priceImpactPercent = Number(impact); const affectedDistricts = districts.split(',').map((item) => item.trim()).filter(Boolean); const recommendedActions = actions.split('\n').map((item) => item.trim()).filter(Boolean); if (!cropName.trim() || !affectedDistricts.length || !recommendedActions.length || !Number.isFinite(surplusVolumeMt) || surplusVolumeMt <= 0 || !Number.isFinite(priceImpactPercent)) { setError('Complete all required fields with valid numbers.'); return; } setBusy(true); setError(null); try { await createSurplusAdvisory({ cropName: cropName.trim(), harvestSeason: harvestSeason.trim() || undefined, affectedDistricts, surplusVolumeMt, level, priceImpactPercent, recommendedActions }); router.back(); } catch (requestError) { setError(getApiErrorMessage(requestError)); } finally { setBusy(false); } };
  return <SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable onPress={router.back}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Issue Surplus Advisory</Text></View><Label text="Crop Name" /><Input placeholder="e.g. Nuwara Eliya Carrots" value={cropName} onChangeText={setCropName} /><Label text="Harvest Season (optional)" /><Input placeholder="e.g. Yala 2026" value={harvestSeason} onChangeText={setHarvestSeason} /><Label text="Affected Districts" /><Input placeholder="Nuwara Eliya, Badulla" value={districts} onChangeText={setDistricts} /><View style={styles.row}><View style={styles.half}><Label text="Surplus Volume (MT)" /><Input keyboardType="decimal-pad" placeholder="45" value={volume} onChangeText={setVolume} /></View><View style={styles.half}><Label text="Price Impact (%)" /><Input keyboardType="numbers-and-punctuation" placeholder="-35" value={impact} onChangeText={setImpact} /></View></View><Label text="Surplus Level" /><View style={styles.choices}>{(['critical', 'moderate', 'normal'] as const).map((item) => <Pressable key={item} onPress={() => setLevel(item)} style={[styles.choice, level === item && styles.activeChoice]}><Text style={[styles.choiceText, level === item && styles.activeChoiceText]}>{item}</Text></Pressable>)}</View><Label text="Recommended Actions" /><TextInput multiline onChangeText={setActions} placeholder={'Enter one action per line\nDelay harvesting where possible\nUse cooperative transport'} placeholderTextColor="#A1A4A1" style={styles.actionsInput} textAlignVertical="top" value={actions} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={busy} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{busy ? 'Issuing...' : 'Issue Market Advisory'}</Text></Pressable></ScrollView></SafeAreaView>;
}
function Label({ text }: { text: string }) { return <Text style={styles.label}>{text}</Text>; }
function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput placeholderTextColor="#A1A4A1" style={styles.input} {...props} />; }
const styles = StyleSheet.create({ safeArea: { backgroundColor: '#FAFCFA', flex: 1 }, content: { padding: 16, paddingBottom: 34 }, header: { alignItems: 'center', flexDirection: 'row', minHeight: 66 }, back: { color: BrandColors.primary, fontSize: 36, marginRight: 11 }, title: { color: BrandColors.primary, fontSize: 19, fontWeight: '800' }, label: { color: '#555855', fontSize: 10, fontWeight: '800', marginBottom: 7, marginTop: 14 }, input: { backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 9, borderWidth: 1, color: '#454845', fontSize: 11, minHeight: 43, paddingHorizontal: 11 }, row: { flexDirection: 'row', gap: 10 }, half: { flex: 1 }, choices: { flexDirection: 'row', gap: 8 }, choice: { borderColor: BrandColors.border, borderRadius: 8, borderWidth: 1, paddingHorizontal: 13, paddingVertical: 9 }, activeChoice: { backgroundColor: BrandColors.primarySurface, borderColor: BrandColors.primary }, choiceText: { color: '#666966', fontSize: 9, fontWeight: '700', textTransform: 'capitalize' }, activeChoiceText: { color: BrandColors.primary }, actionsInput: { backgroundColor: BrandColors.white, borderColor: BrandColors.border, borderRadius: 9, borderWidth: 1, color: '#454845', fontSize: 11, minHeight: 110, padding: 11 }, error: { color: BrandColors.danger, fontSize: 10, marginTop: 11, textAlign: 'center' }, submit: { alignItems: 'center', backgroundColor: BrandColors.primary, borderRadius: 11, marginTop: 16, paddingVertical: 15 }, submitText: { color: BrandColors.white, fontSize: 11, fontWeight: '800' } });
